/** @type {import('tailwindcss').Config} */
const withAlpha = (cssVar) => `rgb(var(${cssVar}) / <alpha-value>)`

export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        brand: withAlpha('--color-brand'),
        'brand-deep': withAlpha('--color-brand-deep'),
        bone: withAlpha('--color-bone'),
        cta: withAlpha('--color-cta'),
        premium: withAlpha('--color-premium'),
        alert: withAlpha('--color-alert'),
        decor: withAlpha('--color-decor'),

        primary: withAlpha('--color-primary'),
        'on-primary': withAlpha('--color-on-primary'),
        'primary-container': withAlpha('--color-primary-container'),
        'on-primary-container': withAlpha('--color-on-primary-container'),
        'inverse-primary': withAlpha('--color-inverse-primary'),

        secondary: withAlpha('--color-secondary'),
        'on-secondary': withAlpha('--color-on-secondary'),
        'secondary-container': withAlpha('--color-secondary-container'),
        'on-secondary-container': withAlpha('--color-on-secondary-container'),

        tertiary: withAlpha('--color-tertiary'),
        'on-tertiary': withAlpha('--color-on-tertiary'),
        'tertiary-container': withAlpha('--color-tertiary-container'),
        'on-tertiary-container': withAlpha('--color-on-tertiary-container'),

        error: withAlpha('--color-error'),
        'on-error': withAlpha('--color-on-error'),
        'error-container': withAlpha('--color-error-container'),
        'on-error-container': withAlpha('--color-on-error-container'),

        background: withAlpha('--color-background'),
        'on-background': withAlpha('--color-on-background'),
        surface: withAlpha('--color-surface'),
        'on-surface': withAlpha('--color-on-surface'),
        'surface-variant': withAlpha('--color-surface-variant'),
        'on-surface-variant': withAlpha('--color-on-surface-variant'),
        'surface-dim': withAlpha('--color-surface-dim'),
        'surface-bright': withAlpha('--color-surface-bright'),
        'surface-container-lowest': withAlpha('--color-surface-container-lowest'),
        'surface-container-low': withAlpha('--color-surface-container-low'),
        'surface-container': withAlpha('--color-surface-container'),
        'surface-container-high': withAlpha('--color-surface-container-high'),
        'surface-container-highest': withAlpha('--color-surface-container-highest'),
        'surface-tint': withAlpha('--color-surface-tint'),

        outline: withAlpha('--color-outline'),
        'outline-variant': withAlpha('--color-outline-variant'),
        'inverse-surface': withAlpha('--color-inverse-surface'),
        'inverse-on-surface': withAlpha('--color-inverse-on-surface'),

        'primary-fixed': withAlpha('--color-primary-fixed'),
        'primary-fixed-dim': withAlpha('--color-primary-fixed-dim'),
        'on-primary-fixed': withAlpha('--color-on-primary-fixed'),
        'on-primary-fixed-variant': withAlpha('--color-on-primary-fixed-variant'),
        'secondary-fixed': withAlpha('--color-secondary-fixed'),
        'secondary-fixed-dim': withAlpha('--color-secondary-fixed-dim'),
        'on-secondary-fixed': withAlpha('--color-on-secondary-fixed'),
        'on-secondary-fixed-variant': withAlpha('--color-on-secondary-fixed-variant'),
        'tertiary-fixed': withAlpha('--color-tertiary-fixed'),
        'tertiary-fixed-dim': withAlpha('--color-tertiary-fixed-dim'),
        'on-tertiary-fixed': withAlpha('--color-on-tertiary-fixed'),
        'on-tertiary-fixed-variant': withAlpha('--color-on-tertiary-fixed-variant'),

        'kelly-green': withAlpha('--color-kelly-green'),
        mint: withAlpha('--color-mint'),
        pistachio: withAlpha('--color-pistachio'),
        'forest-green': withAlpha('--color-forest-green'),
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '24px',
        card: '24px',
        full: '9999px',
      },
      spacing: {
        'stack-sm': '12px',
        'stack-md': '24px',
        'card-padding': '24px',
        'stack-lg': '48px',
        base: '8px',
        'container-margin-desktop': '40px',
        'container-margin-mobile': '20px',
        gutter: '24px',
      },
      fontFamily: {
        'headline-md': ['Montserrat', 'sans-serif'],
        'headline-lg': ['Montserrat', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'display-lg': ['Montserrat', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Montserrat', 'sans-serif'],
      },
      fontSize: {
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
